#!/bin/bash

#./src/booksim ./sims/mycmesh >./sims/cmesh/first.txt &
./src/booksim ./sims/myfbfly
wait
echo ==========================================================================
echo NEXT SIM
echo ==========================================================================
./src/booksim ./sims/
wait
echo done!